name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ubuntu@52.91.215.1/home/ubuntu/hello-world-app

      - name: Install dependencies and restart application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.91.215.1 << 'EOF'
          cd /home/ubuntu/hello-world-app
          npm install
          pm2 restart hello-world-app || pm2 start dist/main.js --name "hello-world-app"
          EOF
