name: Deploy NestJS App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            #!/bin/bash

            # Define project directory
            PROJECT_DIR="/home/ubuntu/nestjsapp"

            # Remove the existing directory if it exists to avoid conflicts
            if [ -d "$PROJECT_DIR" ]; then
              rm -rf "$PROJECT_DIR"
            fi

            # Clone the repository
            git clone https://github.com/haripriya2413/nestjsapp.git "$PROJECT_DIR"

            # Navigate to project directory
            cd "$PROJECT_DIR" || { echo "Directory $PROJECT_DIR does not exist."; exit 1; }

            # Pull the latest changes from the master branch
            git pull origin main

            # Check if package.json exists
            if [ -f "package.json" ]; then
              # Install dependencies
              npm install
            else
              echo "package.json not found in $PROJECT_DIR."
              exit 1
            fi

            # Build the project
            npm run build

            # Check if pm2 is installed, if not install it
            if ! command -v pm2 &> /dev/null; then
              echo "pm2 could not be found, installing..."
              npm install -g pm2
              pm2 startup
            fi

            # Start or restart the application with PM2
            if pm2 describe nestjsapp> /dev/null; then
              pm2 restart nestjsapp"
            else
              pm2 start dist/main.js --name nestjsapp
            fi

            # Save the PM2 process list and corresponding environments
            pm2 save
